"""reusable locations and their scouting plates

Revision ID: 0034
Revises: 0033
Create Date: 2026-08-17

§6 of ``studio/docs/VISUAL_ASSET_LIBRARY.md``: a virtual location department
rather than a folder of attractive photographs. A location is reusable across
scenes and campaigns, may nest (Railway Hotel → front bar, back room, rear car
park), and carries the facts a scene needs before anyone generates into it:
layout, scale anchors, lighting, restrictions, and who owns the rights.

``scout_locations``, not ``locations``. Migration 0029 already added a
``locations`` table, campaign-scoped and cascading away with its campaign --
the same collision as ``characters``, resolved the same way and for the same
reason (ADR-020). A place outlives the campaign that shot there. Campaign
locations gain a nullable ``scout_location_id`` saying which real place they
are.

Rights carry more weight here than anywhere else in the library. Cast frames and
scene masters are generated by the owner; a location plate may be licensed
stock, a commissioned photograph or somebody's holiday snap. §6.4 is explicit
that unknown rights do not stop an asset being held -- they stop it being
promoted to a base master that production reaches. The partial unique index
enforces the other half: one approved base master per location, so "the back
room" resolves the way "the master for pub-1105" does.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0034"
down_revision: str | None = "0033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JSONB = postgresql.JSONB(astext_type=sa.Text())
UUID = postgresql.UUID(as_uuid=True)

# §6.2. Free text would have been wrong here: what class a plate is decides
# whether it can become a base master, and a typo must not quietly promote one.
location_asset_role = postgresql.ENUM(
    "scout_photo",
    "survey_wide",
    "survey_detail",
    "empty_plate",
    "participant_neutral_base",
    "generated_location_plate",
    "approved_base_master",
    "lighting_reference",
    "scale_reference",
    name="location_asset_role",
    create_type=False,
)


def _timestamps() -> tuple[sa.Column[Any], sa.Column[Any]]:
    return (
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )


def upgrade() -> None:
    location_asset_role.create(op.get_bind(), checkfirst=True)
    for event in ("location_registered", "location_asset_linked", "location_master_approved"):
        op.execute(f"ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS '{event}'")

    op.create_table(
        "scout_locations",
        sa.Column("id", UUID, server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("parent_location_id", UUID, nullable=True),
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("location_type", sa.String(length=64), nullable=True),
        sa.Column("region", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("layout_notes", sa.Text(), nullable=True),
        sa.Column("scale_anchor_notes", sa.Text(), nullable=True),
        sa.Column("lighting_notes", sa.Text(), nullable=True),
        sa.Column("continuity_notes", sa.Text(), nullable=True),
        sa.Column("time_of_day_tags", JSONB, server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column("weather_tags", JSONB, server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column(
            "practical_fixtures", JSONB, server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("restrictions", JSONB, server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_scout_locations"),
        sa.ForeignKeyConstraint(
            ["parent_location_id"],
            ["scout_locations.id"],
            name="fk_scout_locations_parent_location_id_scout_locations",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint("slug", name="uq_scout_locations_slug"),
        sa.CheckConstraint("status IN ('active','deprecated')", name="status_known"),
        sa.CheckConstraint("id <> parent_location_id", name="no_self_parent"),
    )
    op.create_index(
        "ix_scout_locations_parent_location_id", "scout_locations", ["parent_location_id"]
    )
    op.create_index("ix_scout_locations_status", "scout_locations", ["status"])

    op.create_table(
        "location_assets",
        sa.Column("id", UUID, server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("location_id", UUID, nullable=False),
        sa.Column("visual_asset_id", UUID, nullable=False),
        sa.Column("role", location_asset_role, nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("camera_position", sa.String(length=200), nullable=True),
        sa.Column("exposure_notes", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_base_master", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        *_timestamps(),
        sa.PrimaryKeyConstraint("id", name="pk_location_assets"),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["scout_locations.id"],
            name="fk_location_assets_location_id_scout_locations",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["visual_asset_id"],
            ["visual_assets.id"],
            name="fk_location_assets_visual_asset_id_visual_assets",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "location_id", "visual_asset_id", name="uq_location_assets_location_id_visual_asset_id"
        ),
    )
    # One approved base master per location: "the back room" has one answer.
    op.create_index(
        "uq_location_assets_one_base_master",
        "location_assets",
        ["location_id"],
        unique=True,
        postgresql_where=sa.text("is_base_master"),
    )
    op.create_index("ix_location_assets_role", "location_assets", ["role"])

    # A campaign's location can now say which real place it is.
    op.add_column("locations", sa.Column("scout_location_id", UUID, nullable=True))
    op.create_foreign_key(
        "fk_locations_scout_location_id_scout_locations",
        "locations",
        "scout_locations",
        ["scout_location_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index("ix_locations_scout_location_id", "locations", ["scout_location_id"])


def downgrade() -> None:
    op.drop_index("ix_locations_scout_location_id", table_name="locations")
    op.drop_constraint(
        "fk_locations_scout_location_id_scout_locations", "locations", type_="foreignkey"
    )
    op.drop_column("locations", "scout_location_id")

    op.drop_index("ix_location_assets_role", table_name="location_assets")
    op.drop_index("uq_location_assets_one_base_master", table_name="location_assets")
    op.drop_table("location_assets")
    op.drop_index("ix_scout_locations_status", table_name="scout_locations")
    op.drop_index("ix_scout_locations_parent_location_id", table_name="scout_locations")
    op.drop_table("scout_locations")
    location_asset_role.drop(op.get_bind(), checkfirst=True)
