# ruff: noqa: E501, RUF001 -- this module embeds a browser page as a string literal.
# Its HTML, CSS and JS are minified onto single lines and cannot be wrapped
# without changing what is served. Same exemption vintage_evidence.py carries.
"""Small Studio workbench for evidence-backed two-part design briefs."""

from __future__ import annotations

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()


@router.get("/vintage-design")
def page() -> HTMLResponse:
    return HTMLResponse(PAGE, headers={"Cache-Control": "no-store"})


PAGE = r"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vintage Design — Shirtfaced Studio</title><style>
:root{font-family:Inter,system-ui,sans-serif;background:#f5f3ee;color:#111}*{box-sizing:border-box}body{margin:0}.shell{max-width:1180px;margin:auto;padding:22px}h1{margin:0;font-size:30px}.sub{color:#666;margin:5px 0 20px}.card{background:#fff;border:1px solid #d7d3ca;border-radius:16px;padding:16px;margin-bottom:14px}label{display:block;font-weight:800;font-size:12px;margin:0 0 6px}select,textarea{width:100%;border:1px solid #bbb;border-radius:10px;background:#fff;padding:11px;font:inherit}textarea{min-height:110px;resize:vertical}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}button{border:1px solid #111;border-radius:10px;background:#111;color:#fff;padding:11px 15px;font-weight:800;cursor:pointer}button.secondary{background:#fff;color:#111}button:disabled{opacity:.45}.summary{display:flex;gap:12px;flex-wrap:wrap;font-size:13px;margin-bottom:12px}.summary b{font-size:16px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:10px}.ev{border:1px solid #ddd;border-radius:11px;overflow:hidden;background:#fafafa}.ev img{display:block;width:100%;aspect-ratio:1/1;object-fit:contain;background:#eee}.ev div{padding:8px;font-size:11px;line-height:1.3}.instruction{padding:11px;border-radius:10px;background:#111;color:#fff;font-size:12px;line-height:1.45}.ok{background:#e8f6e8;border:1px solid #b9d9b9;padding:11px;border-radius:10px;margin-top:10px}.error{background:#fdeaea;border:1px solid #e8bbbb;padding:11px;border-radius:10px;margin-top:10px}.muted{color:#666;font-size:12px}@media(max-width:720px){.shell{padding:14px}.two{grid-template-columns:1fr}.actions button{flex:1}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style></head><body><main class="shell"><h1>Vintage Design</h1><div class="sub">Part 1 chooses proven visual grammar. Part 2 stays original Shirtfaced content.</div><section class="card"><label>Concept</label><select id="concept"><option value="">Choose a concept…</option></select><div class="two" style="margin-top:14px"><div><label>Part 1 — structural evidence query</label><textarea id="structure" placeholder="e.g. 90s skate, small front / large back, illustration-led, 2–3 inks"></textarea></div><div><label>Part 2 — original Shirtfaced content</label><textarea id="creative" placeholder="Concept, joke, character, phrase, subject matter…"></textarea></div></div><div class="actions"><button id="preview">Find evidence</button><button class="secondary" id="create" disabled>Create design attempt</button><button class="secondary" onclick="location.href='/vintage-evidence'">Evidence viewer</button></div><div id="message"></div></section><section class="card" id="result" hidden><div class="summary" id="summary"></div><div class="instruction" id="instruction"></div><div class="grid" id="evidence" style="margin-top:12px"></div></section></main><script>
const $=id=>document.getElementById(id);let concepts=[],bundle=null;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function defaultStructure(c){return [c.title,c.tags?.join(' '),c.treatment_lanes?.join(' '),c.garments?.join(' ')].filter(Boolean).join(' ')}
async function load(){try{concepts=await fetch('/api/concepts?limit=500').then(r=>{if(!r.ok)throw Error('Could not load concepts');return r.json()});for(const c of concepts){const o=document.createElement('option');o.value=c.id;o.textContent=`#${String(c.external_number).padStart(3,'0')} — ${c.title}`;$('concept').append(o)}}catch(e){$('message').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
$('concept').addEventListener('change',()=>{const c=concepts.find(x=>x.id===$('concept').value);if(!c)return;$('structure').value=defaultStructure(c);$('creative').value=c.concept_text||c.title;bundle=null;$('create').disabled=true;$('result').hidden=true;$('message').innerHTML=''})
$('preview').addEventListener('click',async()=>{const structure=$('structure').value.trim(),creative=$('creative').value.trim();if(!structure||!creative){$('message').innerHTML='<div class="error">Both parts need content.</div>';return}$('preview').disabled=true;$('message').innerHTML='<div class="muted">Retrieving retained sold-listing evidence…</div>';try{const r=await fetch('/api/vintage-design/two-part',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({structure_query:structure,creative_query:creative,limit:12})});if(!r.ok)throw Error(await r.text());bundle=await r.json();const p=bundle.part_1_structure,s=p.structure;$('summary').innerHTML=`<span><b>${p.match_count}</b> matched references</span><span><b>${esc(s.dominant_era||'—')}</b> dominant era</span><span><b>${esc(s.dominant_tradition||'—')}</b> tradition</span><span><b>${esc(s.dominant_garment||'—')}</b> garment</span>`;$('instruction').textContent=bundle.combined_instruction;$('evidence').innerHTML=(p.evidence||[]).map(e=>`<article class="ev">${e.images?.[0]?`<img loading="lazy" src="${esc(e.images[0])}">`:''}<div><b>${esc(e.brand||'Unknown')}</b><br>${esc(e.title||'')}<br><span class="muted">${esc(e.era||'')} · ${esc(e.tradition||'')}</span></div></article>`).join('');$('result').hidden=false;$('create').disabled=!$('concept').value;$('message').innerHTML=''}catch(e){$('message').innerHTML=`<div class="error">${esc(e.message)}</div>`}finally{$('preview').disabled=false}})
$('create').addEventListener('click',async()=>{if(!$('concept').value||!bundle)return;$('create').disabled=true;$('message').innerHTML='<div class="muted">Freezing the evidence bundle into a design attempt…</div>';try{const r=await fetch(`/api/vintage-design/concepts/${encodeURIComponent($('concept').value)}/attempts`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({structure_query:$('structure').value.trim(),creative_query:$('creative').value.trim(),evidence_limit:12})});if(!r.ok)throw Error(await r.text());const d=await r.json();$('message').innerHTML=`<div class="ok"><b>Attempt ${d.attempt_number} created.</b> ${d.vintage_match_count} vintage references are frozen into its provenance. Attempt ID: ${esc(d.attempt_id)}</div>`}catch(e){$('message').innerHTML=`<div class="error">${esc(e.message)}</div>`}finally{$('create').disabled=false}})
load();
</script></body></html>"""
