"""Persistence for reviewed social packages and publication jobs."""

from __future__ import annotations

import datetime as dt
import uuid
from enum import StrEnum

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Index, Integer, String, Text, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin


class SocialPostState(StrEnum):
    REVIEW_REQUIRED = "review_required"
    APPROVED = "approved"
    REJECTED = "rejected"
    QUEUED = "queued"
    LIVE = "live"


class PublicationState(StrEnum):
    QUEUED = "queued"
    SCHEDULED = "scheduled"
    HELD = "held"
    PUBLISHING = "publishing"
    PUBLISHED = "published"
    FAILED = "failed"
    CANCELLED = "cancelled"


class SocialChannel(StrEnum):
    INSTAGRAM_FEED = "instagram_feed"
    INSTAGRAM_STORY = "instagram_story"
    INSTAGRAM_REEL = "instagram_reel"
    TIKTOK = "tiktok"


def _enum(enum_type: type[StrEnum], name: str) -> Enum:
    return Enum(enum_type, name=name, values_callable=lambda e: [member.value for member in e])


class SocialPost(Base, TimestampMixin):
    """One immutable-at-approval social package."""

    __tablename__ = "social_posts"
    __table_args__ = (Index("ix_social_posts_state_created_at", "state", text("created_at DESC")),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    source_photo_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("photos.id", ondelete="RESTRICT"), nullable=False
    )
    theme: Mapped[str] = mapped_column(String(32), nullable=False)
    branding: Mapped[str] = mapped_column(String(32), nullable=False)
    caption: Mapped[str] = mapped_column(Text, nullable=False, server_default="")
    campaign_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    state: Mapped[SocialPostState] = mapped_column(
        _enum(SocialPostState, "social_post_state"),
        nullable=False,
        default=SocialPostState.REVIEW_REQUIRED,
        server_default=SocialPostState.REVIEW_REQUIRED.value,
    )
    approved_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    rejected_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))

    derivatives: Mapped[list[SocialDerivative]] = relationship(
        back_populates="post", cascade="all, delete-orphan", order_by="SocialDerivative.created_at"
    )
    jobs: Mapped[list[PublicationJob]] = relationship(
        back_populates="post", cascade="all, delete-orphan", order_by="PublicationJob.created_at"
    )


class SocialDerivative(Base):
    """Exact bytes generated by Social Studio for one output."""

    __tablename__ = "social_derivatives"
    __table_args__ = (
        Index("ix_social_derivatives_post_id", "social_post_id"),
        Index("ix_social_derivatives_sha256", "sha256"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    social_post_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("social_posts.id", ondelete="CASCADE"), nullable=False
    )
    output_key: Mapped[str] = mapped_column(String(64), nullable=False)
    channel: Mapped[SocialChannel] = mapped_column(
        _enum(SocialChannel, "social_channel"), nullable=False
    )
    relative_path: Mapped[str] = mapped_column(String(512), nullable=False, unique=True)
    mime_type: Mapped[str] = mapped_column(String(64), nullable=False)
    width: Mapped[int] = mapped_column(Integer, nullable=False)
    height: Mapped[int] = mapped_column(Integer, nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False)
    filename: Mapped[str] = mapped_column(String(240), nullable=False)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    post: Mapped[SocialPost] = relationship(back_populates="derivatives")
    jobs: Mapped[list[PublicationJob]] = relationship(back_populates="derivative")


class CadencePolicy(Base, TimestampMixin):
    """Replaceable deterministic scheduling policy."""

    __tablename__ = "cadence_policies"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    name: Mapped[str] = mapped_column(String(120), nullable=False, unique=True)
    minimum_spacing_minutes: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("1440")
    )
    preferred_hour_local: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("19"))
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))


class PublicationJob(Base, TimestampMixin):
    """One channel-specific, idempotent publication intent."""

    __tablename__ = "publication_jobs"
    __table_args__ = (
        Index("ix_publication_jobs_state_scheduled_at", "state", "scheduled_at"),
        Index("ix_publication_jobs_post_id", "social_post_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    social_post_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("social_posts.id", ondelete="CASCADE"), nullable=False
    )
    derivative_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("social_derivatives.id", ondelete="RESTRICT"), nullable=False
    )
    channel: Mapped[SocialChannel] = mapped_column(
        _enum(SocialChannel, "social_channel",), nullable=False
    )
    scheduled_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    scheduled_timezone: Mapped[str] = mapped_column(
        String(80), nullable=False, server_default="Australia/Brisbane"
    )
    recommended_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    cadence_policy_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cadence_policies.id", ondelete="SET NULL")
    )
    locked: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    state: Mapped[PublicationState] = mapped_column(
        _enum(PublicationState, "publication_state"),
        nullable=False,
        default=PublicationState.QUEUED,
        server_default=PublicationState.QUEUED.value,
    )
    external_post_id: Mapped[str | None] = mapped_column(String(200), unique=True)
    published_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    failure_reason: Mapped[str | None] = mapped_column(Text)
    retry_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))

    post: Mapped[SocialPost] = relationship(back_populates="jobs")
    derivative: Mapped[SocialDerivative] = relationship(back_populates="jobs")
    cadence_policy: Mapped[CadencePolicy | None] = relationship()
