"""The Visual Asset Library: one asset substrate, plus the cast that uses it.

``studio/docs/VISUAL_ASSET_LIBRARY.md`` §9 and §18. Every production image —
cast reference, location plate, scene master, coverage frame — is a row in
``visual_assets``, and the domain tables link to it. That is what keeps SHA,
provenance, rights and lineage behaving identically across all of them.

Two deliberate departures from the document, both because the thing it proposes
already exists under another name:

* It proposes a ``characters`` table. One is already there, added by migration
  0029, and it is campaign-scoped: a role in one campaign's story, cascading
  away with it. Canonical cast outlives any campaign — Damo is Damo in every
  world he appears in — so the identity layer is :class:`CastMember`, world
  scoped, and ``characters.cast_member_id`` says which real person a story role
  is cast as. Reusing the campaign table would have made deleting a campaign
  delete the cast.
* It proposes ``rights_status`` as a new vocabulary. :class:`LicenceStatus`
  already carries exactly those three states and already means "may this be used
  commercially", so it is reused rather than duplicated.

``image_assets`` is left alone. Its ``attempt_id`` is not nullable and means
"a provider produced this", which an uploaded photograph of a person did not.
"""

from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    event,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.orm.base import NO_VALUE

from app.db.base import Base, TimestampMixin
from app.db.models import SHA256_HEX_LENGTH, _enum
from app.domain.enums import (
    LicenceStatus,
    LocationAssetRole,
    VideoAssetStatus,
    VisualAssetKind,
    VisualAssetSourceType,
    VisualAssetStatus,
)
from app.domain.errors import StudioError


class VisualAsset(Base, TimestampMixin):
    """One immutable image, its identity and its provenance.

    Bytes live in the asset store under ``storage_key``; this row owns
    everything else. §9: ``sha256``, ``byte_size``, the dimensions and the
    storage key are immutable after creation — different bytes are a different
    asset, never an edit of this one. The database enforces that by making the
    hash unique, so ingesting the same file twice returns the existing row
    instead of creating a second identity for it.
    """

    __tablename__ = "visual_assets"
    __table_args__ = (
        UniqueConstraint("sha256", name="uq_visual_assets_sha256"),
        Index("ix_visual_assets_kind_status", "kind", "status"),
        Index("ix_visual_assets_source_type", "source_type"),
        Index("ix_visual_assets_rights_status", "rights_status"),
        CheckConstraint("width > 0 AND height > 0", name="dimensions_positive"),
        CheckConstraint("byte_size > 0", name="byte_size_positive"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    kind: Mapped[VisualAssetKind] = mapped_column(
        _enum(VisualAssetKind, "visual_asset_kind"), nullable=False
    )
    # What the image is of, within its kind. Free text on purpose; see
    # CAST_ASSET_ROLES. Null where the kind alone says everything.
    role: Mapped[str | None] = mapped_column(String(64))
    # Relative to ASSETS_ROOT, so the same row works on any host.
    storage_key: Mapped[str] = mapped_column(String(512), nullable=False)
    sha256: Mapped[str] = mapped_column(String(SHA256_HEX_LENGTH), nullable=False)
    mime_type: Mapped[str] = mapped_column(String(64), nullable=False)
    width: Mapped[int] = mapped_column(Integer, nullable=False)
    height: Mapped[int] = mapped_column(Integer, nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False)
    source_type: Mapped[VisualAssetSourceType] = mapped_column(
        _enum(VisualAssetSourceType, "visual_asset_source_type"), nullable=False
    )
    provider: Mapped[str | None] = mapped_column(String(64))
    model: Mapped[str | None] = mapped_column(String(128))
    provider_request_id: Mapped[str | None] = mapped_column(String(128))
    prompt_hash: Mapped[str | None] = mapped_column(String(SHA256_HEX_LENGTH))
    status: Mapped[VisualAssetStatus] = mapped_column(
        _enum(VisualAssetStatus, "visual_asset_status"),
        nullable=False,
        default=VisualAssetStatus.PENDING,
        server_default=VisualAssetStatus.PENDING.value,
    )
    # Verified by default: everything in this library is invented here. The
    # worlds, the cast, the locations, the masters and the coverage are all
    # generated by the owner, there are no photographs of real people, and there
    # is no third party to have a claim. Owner's ruling, 17 August 2026.
    #
    # The column stays because a licence is a fact worth recording, and because
    # REFUSED remains meaningful if something ever does come in from outside.
    rights_status: Mapped[LicenceStatus] = mapped_column(
        _enum(LicenceStatus, "licence_status"),
        nullable=False,
        default=LicenceStatus.VERIFIED,
        server_default=LicenceStatus.VERIFIED.value,
    )
    rights_metadata: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        "metadata_json", JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    description: Mapped[str | None] = mapped_column(Text)
    approved_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    approved_by: Mapped[str | None] = mapped_column(String(64))

    @property
    def aspect_ratio(self) -> float:
        """Width over height. Derived, never stored: it cannot disagree this way."""
        return self.width / self.height

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<VisualAsset {self.kind.value!r} {self.role!r} {self.sha256[:12]}>"


class AssetLineage(Base):
    """How one asset came from another.

    §9.1. A coverage frame's parent is its scene master; a scene master's parent
    is the location plate it was composited into. Stored as edges rather than
    inferred from filenames, which is what the current tooling does and what
    stops being true the moment a file is renamed.
    """

    __tablename__ = "asset_lineage"
    __table_args__ = (
        UniqueConstraint(
            "parent_asset_id",
            "child_asset_id",
            "relationship",
            name="uq_asset_lineage_parent_asset_id_child_asset_id_relationship",
        ),
        CheckConstraint("parent_asset_id <> child_asset_id", name="no_self_lineage"),
        Index("ix_asset_lineage_child_asset_id", "child_asset_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    parent_asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visual_assets.id", ondelete="RESTRICT"), nullable=False
    )
    child_asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visual_assets.id", ondelete="CASCADE"), nullable=False
    )
    # crop / edit / generated_from / composited_into / upscaled / colour_corrected.
    relationship_kind: Mapped[str] = mapped_column("relationship", String(48), nullable=False)
    operation_metadata: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class CastMember(Base, TimestampMixin):
    """A canonical person in the universe, and the owner of their references.

    Identity and descriptive canon live here. The photographs are separate
    assets linked through :class:`CastMemberAsset`, so a member can have three
    references or twenty without the schema changing shape, §5.1.

    ``world_id`` is nullable: a member may be global, reusable across worlds.
    """

    __tablename__ = "cast_members"
    __table_args__ = (
        UniqueConstraint("world_id", "slug", name="uq_cast_members_world_id_slug"),
        Index("ix_cast_members_status", "status"),
        CheckConstraint("status IN ('active','deprecated')", name="status_known"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    world_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("worlds.id", ondelete="CASCADE")
    )
    slug: Mapped[str] = mapped_column(String(64), nullable=False)
    display_name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    # Age band, build, hair, marks — the continuity facts that must not drift.
    canonical_metadata: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    status: Mapped[str] = mapped_column(String(32), nullable=False, server_default="active")

    assets: Mapped[list[CastMemberAsset]] = relationship(
        back_populates="cast_member",
        cascade="all, delete-orphan",
        order_by="CastMemberAsset.sort_order",
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<CastMember {self.slug!r}>"


class CastMemberAsset(Base, TimestampMixin):
    """One reference photograph, in one role, for one cast member.

    The link carries the role, the ordering and the primary badge, because they
    are facts about this member's use of the image rather than about the image.
    The same photograph could legitimately be filed under two members — a
    two-hander — without either of them owning it.
    """

    __tablename__ = "cast_member_assets"
    __table_args__ = (
        UniqueConstraint(
            "cast_member_id",
            "visual_asset_id",
            name="uq_cast_member_assets_cast_member_id_visual_asset_id",
        ),
        # One primary per role per member. A second "the neutral head shot" is
        # ambiguity the renderer would have to resolve by guessing.
        Index(
            "uq_cast_member_assets_primary_per_role",
            "cast_member_id",
            "role",
            unique=True,
            postgresql_where=text("is_primary"),
        ),
        Index("ix_cast_member_assets_visual_asset_id", "visual_asset_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    cast_member_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cast_members.id", ondelete="CASCADE"), nullable=False
    )
    visual_asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visual_assets.id", ondelete="RESTRICT"), nullable=False
    )
    role: Mapped[str] = mapped_column(String(64), nullable=False)
    sort_order: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    is_primary: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    notes: Mapped[str | None] = mapped_column(Text)

    cast_member: Mapped[CastMember] = relationship(back_populates="assets")
    asset: Mapped[VisualAsset] = relationship(lazy="joined")


class ScoutLocation(Base, TimestampMixin):
    """A reusable place, §6.1, and the facts a scene needs before generating.

    Nests: a pub is a location and its back room is another, so a scene can be
    built into the room while the building carries what is true of all of it.

    ``scout_locations``, not 0029's campaign-scoped ``locations``. A place
    outlives the campaign that shot there, the same argument as ADR-020 makes
    for cast, and ``locations.scout_location_id`` links the two.
    """

    __tablename__ = "scout_locations"
    __table_args__ = (
        UniqueConstraint("slug", name="uq_scout_locations_slug"),
        Index("ix_scout_locations_parent_location_id", "parent_location_id"),
        Index("ix_scout_locations_status", "status"),
        CheckConstraint("status IN ('active','deprecated')", name="status_known"),
        CheckConstraint("id <> parent_location_id", name="no_self_parent"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    parent_location_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scout_locations.id", ondelete="RESTRICT")
    )
    slug: Mapped[str] = mapped_column(String(96), nullable=False)
    display_name: Mapped[str] = mapped_column(String(200), nullable=False)
    location_type: Mapped[str | None] = mapped_column(String(64))
    region: Mapped[str | None] = mapped_column(String(120))
    description: Mapped[str | None] = mapped_column(Text)
    layout_notes: Mapped[str | None] = mapped_column(Text)
    scale_anchor_notes: Mapped[str | None] = mapped_column(Text)
    lighting_notes: Mapped[str | None] = mapped_column(Text)
    continuity_notes: Mapped[str | None] = mapped_column(Text)
    time_of_day_tags: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    weather_tags: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    practical_fixtures: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    restrictions: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    status: Mapped[str] = mapped_column(String(32), nullable=False, server_default="active")

    parent: Mapped[ScoutLocation | None] = relationship(remote_side="ScoutLocation.id")
    assets: Mapped[list[LocationAsset]] = relationship(
        back_populates="location",
        cascade="all, delete-orphan",
        order_by="LocationAsset.sort_order",
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<ScoutLocation {self.slug!r}>"


class LocationAsset(Base, TimestampMixin):
    """One scouting image of one place, in one class, §6.2.

    ``is_base_master`` is the promotion §6.4 gates on rights: a plate with
    unknown rights can be held, looked at and compared, and cannot become the
    thing a scene is generated into.
    """

    __tablename__ = "location_assets"
    __table_args__ = (
        UniqueConstraint(
            "location_id", "visual_asset_id", name="uq_location_assets_location_id_visual_asset_id"
        ),
        Index(
            "uq_location_assets_one_base_master",
            "location_id",
            unique=True,
            postgresql_where=text("is_base_master"),
        ),
        Index("ix_location_assets_role", "role"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    location_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scout_locations.id", ondelete="CASCADE"), nullable=False
    )
    visual_asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visual_assets.id", ondelete="RESTRICT"), nullable=False
    )
    role: Mapped[LocationAssetRole] = mapped_column(
        _enum(LocationAssetRole, "location_asset_role"), nullable=False
    )
    sort_order: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    camera_position: Mapped[str | None] = mapped_column(String(200))
    exposure_notes: Mapped[str | None] = mapped_column(Text)
    notes: Mapped[str | None] = mapped_column(Text)
    is_base_master: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )

    location: Mapped[ScoutLocation] = relationship(back_populates="assets")
    asset: Mapped[VisualAsset] = relationship(lazy="joined")


class SceneMaster(Base, TimestampMixin):
    """The approved spatial truth for one scene, §7.

    Minimal on purpose: ``scene_key`` is the scene's string identity —
    ``W01-P28`` — because §7's ``scene_id`` foreign key wants the campaign
    scene records that nothing populates yet. When they exist this gains the
    key; until then a string is what the coverage tool, the renderer scripts
    and the Veo runs already agree on, and inventing a join to an empty table
    would not make the resolution any more correct.

    The partial unique index is the point of the table. Exactly one master per
    scene may be approved, so "the master for W01-P28" is a question with one
    answer rather than a directory listing with a preference order.
    """

    __tablename__ = "scene_masters"
    __table_args__ = (
        UniqueConstraint("visual_asset_id", name="uq_scene_masters_visual_asset_id"),
        Index(
            "uq_scene_masters_one_approved_per_scene",
            "scene_key",
            unique=True,
            postgresql_where=text("status = 'approved'"),
        ),
        Index("ix_scene_masters_scene_key_status", "scene_key", "status"),
        CheckConstraint(
            "status IN ('candidate','approved','superseded','rejected','deprecated')",
            name="status_known",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    scene_key: Mapped[str] = mapped_column(String(96), nullable=False)
    visual_asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visual_assets.id", ondelete="RESTRICT"), nullable=False
    )
    status: Mapped[str] = mapped_column(String(32), nullable=False, server_default="candidate")
    # The master this one replaced. A new approved master supersedes rather than
    # overwrites, so a finished clip's lineage stays readable.
    parent_master_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scene_masters.id", ondelete="SET NULL")
    )
    notes: Mapped[str | None] = mapped_column(Text)
    approved_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    approved_by: Mapped[str | None] = mapped_column(String(64))

    asset: Mapped[VisualAsset] = relationship(lazy="joined")

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<SceneMaster {self.scene_key!r} {self.status!r}>"


class SceneContactSheet(Base, TimestampMixin):
    """A Nano coverage sheet: nine observations of one approved master.

    Persisted as an artefact rather than a preview, because the pipeline
    contract §6 says so and because the panel a shot claims to be means nothing
    once the sheet it was chosen from is gone.

    One approved sheet per master, for the same reason there is one approved
    master per scene: the selected observation needs one authority.
    """

    __tablename__ = "scene_contact_sheets"
    __table_args__ = (
        UniqueConstraint("visual_asset_id", name="uq_scene_contact_sheets_visual_asset_id"),
        Index(
            "uq_scene_contact_sheets_one_approved_per_master",
            "scene_master_id",
            unique=True,
            postgresql_where=text("status = 'approved'"),
        ),
        CheckConstraint(
            "status IN ('candidate','approved','superseded','rejected')", name="status_known"
        ),
        CheckConstraint("rows > 0 AND columns > 0", name="grid_positive"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    scene_master_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scene_masters.id", ondelete="RESTRICT"), nullable=False
    )
    visual_asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visual_assets.id", ondelete="RESTRICT"), nullable=False
    )
    label: Mapped[str] = mapped_column(String(96), nullable=False)
    rows: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("3"))
    columns: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("3"))
    status: Mapped[str] = mapped_column(String(32), nullable=False, server_default="candidate")
    prompt_template: Mapped[str | None] = mapped_column(String(200))
    resolved_prompt_sha256: Mapped[str | None] = mapped_column(String(SHA256_HEX_LENGTH))
    # What each numbered panel is meant to observe, from the scene's own prompt.
    # Stored so a person choosing panel 5 can see it should be Emma and Brock.
    panel_plan: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    notes: Mapped[str | None] = mapped_column(Text)
    approved_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    approved_by: Mapped[str | None] = mapped_column(String(64))

    master: Mapped[SceneMaster] = relationship(lazy="joined")
    asset: Mapped[VisualAsset] = relationship(lazy="joined")

    @property
    def panels(self) -> int:
        return self.rows * self.columns

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<SceneContactSheet {self.label!r} {self.rows}x{self.columns} {self.status!r}>"


class CoverageFrame(Base, TimestampMixin):
    """One named 9:16 observation of a scene master, §8.

    The crop box and the parent's hash are both stored, so the frame can be
    reproduced from the master byte for byte and checked against what it claims.
    ``source_master_sha256`` is not derivable from ``scene_master_id``: a master
    can be superseded after a frame was cut from it, and the difference between
    "this master" and "this master as it was then" is the whole point.
    """

    __tablename__ = "coverage_frames"
    __table_args__ = (
        UniqueConstraint("visual_asset_id", name="uq_coverage_frames_visual_asset_id"),
        UniqueConstraint("scene_master_id", "name", name="uq_coverage_frames_scene_master_id_name"),
        Index("ix_coverage_frames_scene_master_id_name", "scene_master_id", "name"),
        Index("ix_coverage_frames_approved_for_veo", "approved_for_veo"),
        Index(
            "uq_coverage_frames_contact_sheet_id_panel",
            "contact_sheet_id",
            "panel",
            unique=True,
            postgresql_where=text("contact_sheet_id IS NOT NULL"),
        ),
        CheckConstraint(
            "width IS NULL OR height IS NULL OR (width > 0 AND height > 0)",
            name="dimensions_positive",
        ),
        CheckConstraint(
            "(x IS NULL OR x >= 0) AND (y IS NULL OR y >= 0)", name="origin_not_negative"
        ),
        CheckConstraint(
            "(x IS NOT NULL AND y IS NOT NULL AND width IS NOT NULL AND height IS NOT NULL)"
            " OR (contact_sheet_id IS NOT NULL AND panel IS NOT NULL)",
            name="crop_or_panel",
        ),
        CheckConstraint("panel IS NULL OR panel > 0", name="panel_positive"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    scene_master_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scene_masters.id", ondelete="RESTRICT"), nullable=False
    )
    visual_asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("visual_assets.id", ondelete="RESTRICT"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(96), nullable=False)
    aspect_ratio: Mapped[str] = mapped_column(String(16), nullable=False, server_default="9:16")
    # A crop carries its box. A Nano extraction carries a sheet and a panel and
    # no box at all -- it is generated, so coordinates could neither identify it
    # nor reproduce it. The check constraint requires one shape or the other.
    x: Mapped[int | None] = mapped_column(Integer)
    y: Mapped[int | None] = mapped_column(Integer)
    width: Mapped[int | None] = mapped_column(Integer)
    height: Mapped[int | None] = mapped_column(Integer)
    contact_sheet_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scene_contact_sheets.id", ondelete="RESTRICT")
    )
    panel: Mapped[int | None] = mapped_column(Integer)
    source_master_sha256: Mapped[str] = mapped_column(String(SHA256_HEX_LENGTH), nullable=False)
    frame_sha256: Mapped[str] = mapped_column(String(SHA256_HEX_LENGTH), nullable=False)
    operation: Mapped[str] = mapped_column(String(32), nullable=False, server_default="crop_only")
    # Veo takes an approved frame and nothing else, §15 Phase E.
    approved_for_veo: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    notes: Mapped[str | None] = mapped_column(Text)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        "metadata_json", JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    master: Mapped[SceneMaster] = relationship(lazy="joined", foreign_keys=[scene_master_id])
    asset: Mapped[VisualAsset] = relationship(lazy="joined", foreign_keys=[visual_asset_id])
    contact_sheet: Mapped[SceneContactSheet | None] = relationship(
        lazy="joined", foreign_keys=[contact_sheet_id]
    )

    @property
    def is_extraction(self) -> bool:
        """Generated from a panel rather than cut from the master."""
        return self.contact_sheet_id is not None

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        where = f"panel {self.panel}" if self.is_extraction else f"{self.width}x{self.height}"
        return f"<CoverageFrame {self.name!r} {where}>"


class GenerationCall(Base):
    """One provider call, kept whether it worked or not.

    §6 of the Nano contract wants each stage persisted as an attempt with its
    prompt, model, inputs and output. The assets carry half of that; this is the
    other half, and it is the only place a refusal survives — which is the
    record worth having, because a prompt the model rejects is a fact about the
    prompt.
    """

    __tablename__ = "generation_calls"
    __table_args__ = (
        Index("ix_generation_calls_scene_key_created_at", "scene_key", text("created_at DESC")),
        Index("ix_generation_calls_operation", "operation"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    provider: Mapped[str] = mapped_column(String(32), nullable=False)
    model: Mapped[str] = mapped_column(String(128), nullable=False)
    operation: Mapped[str] = mapped_column(String(48), nullable=False)
    scene_key: Mapped[str | None] = mapped_column(String(96))
    subject: Mapped[str | None] = mapped_column(String(96))
    prompt_sha256: Mapped[str | None] = mapped_column(String(SHA256_HEX_LENGTH))
    input_asset_ids: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    output_asset_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    succeeded: Mapped[bool] = mapped_column(Boolean, nullable=False)
    failure: Mapped[str | None] = mapped_column(Text)
    duration_ms: Mapped[int | None] = mapped_column(Integer)
    actor: Mapped[str] = mapped_column(String(64), nullable=False, server_default="owner")
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class VideoAsset(Base, TimestampMixin):
    """One immutable clip.

    A third sibling beside images and audio. A clip knows its duration, its
    frame rate and whether it still carries the sound the model generated —
    none of which means anything on a still, and the last of which cannot be
    told from the filename.
    """

    __tablename__ = "video_assets"
    __table_args__ = (
        UniqueConstraint("sha256", name="uq_video_assets_sha256"),
        CheckConstraint("byte_size > 0", name="byte_size_positive"),
        CheckConstraint("duration_ms IS NULL OR duration_ms > 0", name="duration_positive"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    storage_key: Mapped[str] = mapped_column(String(512), nullable=False)
    sha256: Mapped[str] = mapped_column(String(SHA256_HEX_LENGTH), nullable=False)
    mime_type: Mapped[str] = mapped_column(String(64), nullable=False)
    byte_size: Mapped[int] = mapped_column(Integer, nullable=False)
    duration_ms: Mapped[int | None] = mapped_column(Integer)
    width: Mapped[int | None] = mapped_column(Integer)
    height: Mapped[int | None] = mapped_column(Integer)
    frame_rate: Mapped[Decimal | None] = mapped_column(Numeric(6, 3))
    has_audio: Mapped[bool | None] = mapped_column(Boolean)
    provider: Mapped[str | None] = mapped_column(String(64))
    model: Mapped[str | None] = mapped_column(String(128))
    status: Mapped[VideoAssetStatus] = mapped_column(
        _enum(VideoAssetStatus, "video_asset_status"),
        nullable=False,
        default=VideoAssetStatus.PENDING,
        server_default=VideoAssetStatus.PENDING.value,
    )
    rights_status: Mapped[LicenceStatus] = mapped_column(
        _enum(LicenceStatus, "licence_status"),
        nullable=False,
        default=LicenceStatus.VERIFIED,
        server_default=LicenceStatus.VERIFIED.value,
    )
    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        "metadata_json", JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    approved_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    approved_by: Mapped[str | None] = mapped_column(String(64))

    @property
    def duration_seconds(self) -> float | None:
        return None if self.duration_ms is None else self.duration_ms / 1000


class MotionTake(Base, TimestampMixin):
    """One attempt at animating one shot.

    Plural on purpose. SHOTLIST.md asks for six to eight seconds a shot and
    expects one and a half to four of them to survive, so most takes are wrong
    and the wrong ones are worth keeping: a rejected take is the cheapest
    evidence there is about what the motion prompt does. A rerun is the next
    attempt number, never an overwrite.

    ``first_frame_sha256`` is the still that was actually sent. It is stored
    beside the foreign key because a shot can be re-extracted, and a take
    animated from the previous still is not a take of the current one.
    """

    __tablename__ = "motion_takes"
    __table_args__ = (
        UniqueConstraint("video_asset_id", name="uq_motion_takes_video_asset_id"),
        UniqueConstraint(
            "coverage_frame_id", "attempt", name="uq_motion_takes_coverage_frame_id_attempt"
        ),
        Index("ix_motion_takes_coverage_frame_id_attempt", "coverage_frame_id", "attempt"),
        Index(
            "uq_motion_takes_one_keeper_per_frame",
            "coverage_frame_id",
            unique=True,
            postgresql_where=text("status = 'keeper'"),
        ),
        CheckConstraint("attempt > 0", name="attempt_positive"),
        CheckConstraint("status IN ('pending','keeper','rejected')", name="status_known"),
        CheckConstraint(
            "keeper_from_ms IS NULL OR keeper_to_ms IS NULL OR keeper_to_ms > keeper_from_ms",
            name="keeper_range_ordered",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    coverage_frame_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("coverage_frames.id", ondelete="RESTRICT"), nullable=False
    )
    video_asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("video_assets.id", ondelete="RESTRICT"), nullable=False
    )
    attempt: Mapped[int] = mapped_column(Integer, nullable=False)
    prompt_sha256: Mapped[str | None] = mapped_column(String(SHA256_HEX_LENGTH))
    first_frame_sha256: Mapped[str] = mapped_column(String(SHA256_HEX_LENGTH), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, server_default="pending")
    keeper_from_ms: Mapped[int | None] = mapped_column(Integer)
    keeper_to_ms: Mapped[int | None] = mapped_column(Integer)
    notes: Mapped[str | None] = mapped_column(Text)
    decided_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))
    decided_by: Mapped[str | None] = mapped_column(String(64))

    frame: Mapped[CoverageFrame] = relationship(lazy="joined")
    video: Mapped[VideoAsset] = relationship(lazy="joined")

    @property
    def keeper_length_ms(self) -> int | None:
        if self.keeper_from_ms is None or self.keeper_to_ms is None:
            return None
        return self.keeper_to_ms - self.keeper_from_ms


class Tag(Base):
    """A reusable label, §9.2: ``pub``, ``night``, ``2.39``, ``production-safe``."""

    __tablename__ = "tags"
    __table_args__ = (UniqueConstraint("slug", name="uq_tags_slug"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    slug: Mapped[str] = mapped_column(String(64), nullable=False)
    label: Mapped[str] = mapped_column(String(120), nullable=False)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class VisualAssetTag(Base):
    """Which tags an asset carries."""

    __tablename__ = "visual_asset_tags"

    visual_asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("visual_assets.id", ondelete="CASCADE"),
        primary_key=True,
    )
    tag_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tags.id", ondelete="CASCADE"), primary_key=True
    )


class AssetIsImmutable(StudioError):
    """Something tried to change what an asset's bytes are."""


# §9: the hash, the size, the dimensions and the key are fixed at creation.
# Different bytes are a different asset. A CHECK constraint cannot express
# "never changes", so the rule is enforced where the change would be made.
IMMUTABLE_ASSET_FIELDS = ("sha256", "byte_size", "width", "height", "storage_key", "mime_type")


def _refuse_mutation(target: VisualAsset, value: Any, old: Any, _initiator: Any) -> Any:
    """Reject an edit to an immutable field once the row exists."""
    if old is NO_VALUE or old is None or old == value:
        return value
    raise AssetIsImmutable(
        f"Asset {target.sha256[:12]}: bytes and their measurements cannot be edited. "
        "Ingest the new image as its own asset and record the lineage."
    )


for _field in IMMUTABLE_ASSET_FIELDS:
    event.listen(getattr(VisualAsset, _field), "set", _refuse_mutation, retval=True)
